name: Terraform AWS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify your desired Terraform version

    # Terraform Init
    - name: Terraform Init
      run: terraform init

    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      if: github.event_name == 'pull_request'

    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
      if: github.event_name == 'push'

    # Show Instance IP
    - name: Show Instance IP
      run: terraform output instance_public_ip
      if: github.event_name == 'push'
