name: Terraform Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5  # Specify the Terraform version you want to use

      # Step 3: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: AKIA47CRWXSP6VFZE2HR
          aws_secret_access_key: XIjdsiLEWxttIQflr308aF3L279ADpyOstT/zYOZ
          aws_region: "us-east-1"  # Replace with your region

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        # Remove `-auto-approve` if you want manual approval

      # Optional Step 7: Terraform Destroy (in case you want to clean up resources)
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
