name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Make sure this matches your region
          
      - name: Install Terraform
        run: |
          curl -LO https://github.com/hashicorp/terraform/releases/download/v1.3.7/terraform_1.3.7_linux_amd64.zip
          unzip terraform_1.3.7_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Run Terraform init
        run: terraform init

      - name: Run Terraform plan
        run: terraform plan

      - name: Run Terraform apply
        run: terraform apply -auto-approve
